#!/usr/bin/env python3
"""Convert a record-build debugger session log (containing `m 9000 800` and
`m 8100 20` dumps) into src/replay_data.asm for a SPIKE_REPLAY build.

Usage: mk_replay.py session.log > src/replay_data.asm
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from crc_trace_diff import parse  # noqa: E402  (same dump format)


def main():
    mem = parse(sys.argv[1])
    ticks = mem.get(0x8108, 0) | (mem.get(0x8109, 0) << 8)
    n = min(ticks, 0x400)
    print(f"; Generated by tools/mk_replay.py -- {n} recorded game ticks")
    print("REPLAY_TBL:")
    for t in range(0x400):
        slot = 0x9000 + (t % 0x400) * 2
        l = mem.get(slot, 0x40) & 0xFF
        r = mem.get(slot + 1, 0x40) & 0xFF
        print(f"        DECLE   ${l:02X}, ${r:02X}\t; tick {t}")


if __name__ == "__main__":
    main()
